name: Codacy Coverage

on:
  push:
    branches:
      #- main
      - codacytest

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov

      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=main tests/ --cov-report=xml

      - name: Verify coverage report exists
        run: |
          ls -la coverage.xml

      - name: Debug file structure
        run: |
          echo "Current directory: $(pwd)"
          ls -al $(pwd)

      - name: Download Codacy Coverage Reporter
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -L https://coverage.codacy.com/get.sh -o get_codacy_reporter.sh
          bash get_codacy_reporter.sh

      - name: Run Codacy Coverage Reporter
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          REPORT_PATH=$(pwd)/coverage.xml
          $HOME/.cache/codacy/coverage-reporter/$(cat $HOME/.cache/codacy/coverage-reporter/codacy-coverage-reporter-version)/codacy-coverage-reporter report -r ${REPORT_PATH}
