name: Codacy Coverage

on:
  push:
    branches:
      #- main
      - codacytest

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov

      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=main tests/ --cov-report=xml

      - name: Verify coverage report exists
        run: |
          ls -la coverage.xml

      - name: Upload coverage report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash
          bash codacy-coverage-reporter report -r $(pwd)/coverage.xml
