name: Codacy Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install coverage pytest pytest-cov

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=. --cov-report=xml

      - name: Download Codacy Coverage Reporter
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash

      - name: Run Codacy Coverage Reporter with coverage report
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          ./codacy-coverage-reporter report -l Python -r coverage.xml
